# Server configuration
server:
  port: 8080
# Logging configuration
logging:
  level:
    root: info
# OpenAPI configuration localhost:8080/mavidev-swagger-ui
springdoc:
  swagger-ui:
    path: /mavidev-swagger-ui

spring:
  profiles:
    active: ${ENV:dev}
